---
abstract: unknown
author:
  - 'Kang-min Liu'
build_requires:
  ExtUtils::MakeMaker: '6.59'
configure_requires:
  CPAN::Meta: '0'
  ExtUtils::MakeMaker: '6.59'
dynamic_config: '0'
generated_by: 'Module::Install version 1.12, CPAN::Meta::Converter version 2.142690'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Sitebrew
no_index:
  directory:
    - inc
requires:
  DateTime: '0'
  DateTime::Format::Mail: '0'
  DateTime::TimeZone: '0'
  DateTimeX::Easy: '0'
  Digest::SHA1: '0'
  Encode: '0'
  ExtUtils::MakeMaker: '0'
  File::Copy: '0'
  File::Find: '0'
  File::Slurp: '0'
  File::stat: '0'
  IO::All: '0'
  List::MoreUtils: '0'
  Moose: '0'
  MooseX::Singleton: '0'
  MooseX::Types::URI: '0'
  Parallel::ForkManager: '0'
  Text::Markdown: '0'
  Text::Xslate: '0'
  Web::Query: '0'
  XML::Feed: '0'
  YAML: '0'
  namespace::autoclean: '0'
  perl: v5.14.0
resources:
  license: http://opensource.org/licenses/mit-license.php
  repository: https://github.com/gugod/sitebrew
version: '1.0'
x_module_name: Sitebrew
