name: install

on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Perl environment
        uses: shogo82148/actions-setup-perl@v1.6.2

      - name: Install Dependencies
        run: |
          cpanm -q -n --no-man-pages App::cpm && \
          cpm install -g

      - name: Run help
        run: |
          perl scripts/sitebrew help
